INSERT INTO cargo (nome_cargo, cod_cargo, turno, id_funcionario)
VALUES
  ('Vendedor', 1, 'D', 1),
  ('Gerente de Vendas', 2, 'D', 2),
  ('Consultor de Vendas', 3, 'N', 3),
  ('Assistente de Vendas', 4, 'N', 4),
  ('Gerente de Showroom', 5, 'D', 5),
  ('Consultor Financeiro', 6, 'N', 6),
  ('Assistente Administrativo', 7, 'D', 7),
  ('Recepcionista', 8, 'N', 8),
  ('Supervisor de Vendas', 9, 'D', 9),
  ('Consultor de Crédito', 10, 'N', 10),
  ('Especialista em Financiamento', 11, 'D', 11),
  ('Coordenador de Marketing', 12, 'N', 12),
  ('Técnico em Manutenção', 13, 'D', 13),
  ('Supervisor de Manutenção', 14, 'N', 14),
  ('Assistente de Manutenção', 15, 'D', 15),
  ('Gerente de Manutenção', 16, 'N', 16),
  ('Consultor de Manutenção', 17, 'D', 17),
  ('Especialista em Peças', 18, 'N', 18),
  ('Assistente de Peças', 19, 'D', 19),
  ('Gerente de Peças', 20, 'N', 20),
  ('Coordenador de Serviços', 21, 'D', 21),
  ('Assistente de Serviços', 22, 'N', 22),
  ('Gerente de Serviços', 23, 'D', 23),
  ('Consultor de Serviços', 24, 'N', 24),
  ('Especialista em Diagnóstico', 25, 'D', 25),
  ('Técnico de Diagnóstico', 26, 'N', 26),
  ('Supervisor de Diagnóstico', 27, 'D', 27),
  ('Assistente de Diagnóstico', 28, 'N', 28),
  ('Gerente de Diagnóstico', 29, 'D', 29),
  ('Analista de Marketing', 30, 'N', 30),
  ('Especialista em Marketing Digital', 31, 'D', 31),
  ('Assistente de Marketing', 32, 'N', 32),
  ('Coordenador de Marketing Digital', 33, 'D', 33),
  ('Analista de Vendas', 34, 'N', 34),
  ('Supervisor de Atendimento ao Cliente', 35, 'D', 35),
  ('Assistente de Atendimento ao Cliente', 36, 'N', 36),
  ('Gerente de Atendimento ao Cliente', 37, 'D', 37),
  ('Consultor de Atendimento ao Cliente', 38, 'N', 38),
  ('Especialista em Atendimento ao Cliente', 39, 'D', 39),
  ('Técnico de Atendimento ao Cliente', 40, 'N', 40),
  ('Supervisor de Logística', 41, 'D', 41),
  ('Assistente de Logística', 42, 'N', 42),
  ('Gerente de Logística', 43, 'D', 43),
  ('Analista de Logística', 44, 'N', 44),
  ('Coordenador de Logística', 45, 'D', 45),
  ('Especialista em Logística', 46, 'N', 46),
  ('Consultor de Logística', 47, 'D', 47),
  ('Supervisor de Almoxarifado', 48, 'N', 48),
  ('Assistente de Almoxarifado', 49, 'D', 49),
  ('Gerente de Almoxarifado', 50, 'N', 50),
  ('Analista de Recursos Humanos', 51, 'D', 51),
  ('Coordenador de Recursos Humanos', 52, 'N', 52),
  ('Especialista em Recursos Humanos', 53, 'D', 53),
  ('Assistente de Recursos Humanos', 54, 'N', 54),
  ('Gerente de Recursos Humanos', 55, 'D', 55),
  ('Consultor de Recursos Humanos', 56, 'N', 56),
  ('Supervisor de TI', 57, 'D', 57),
  ('Assistente de TI', 58, 'N', 58),
  ('Gerente de TI', 59, 'D', 59),
  ('Analista de TI', 60, 'N', 60),
  ('Coordenador de TI', 61, 'D', 61),
  ('Especialista em TI', 62, 'N', 62),
  ('Consultor de TI', 63, 'D', 63),
  ('Supervisor de Compras', 64, 'N', 64),
  ('Assistente de Compras', 65, 'D', 65),
  ('Gerente de Compras', 66, 'N', 66),
  ('Analista de Compras', 67, 'D', 67),
  ('Coordenador de Compras', 68, 'N', 68),
  ('Especialista em Compras', 69, 'D', 69),
  ('Consultor de Compras', 70, 'N', 70);
