-- COMANDOS DATABASE
CREATE DATABASE EXEMPLO1

DROP DATABASE EXEMPLO1

-- COMANDOS PARA CRIAR TABELAS
CREATE TABLE FUNCIONARIOS (
	id_funcionarios SERIAL NOT NULL PRIMARY KEY,
	nome_funcionarios VARCHAR(100) NOT NULL,
	status_funcionarios INT NOT NULL,
	cidade_funcionarios VARCHAR(50) NOT NULL
)

CREATE TABLE produtos (
	id_produtos INT NOT NULL PRIMARY KEY,
	nome_produto VARCHAR(255),
	quantidade_produto INT NOT NULL,
	valor_produto DECIMAL(7,2) NOT NULL,
	validade_produto DATE NOT NULL
)


-- COMANDOS PARA VISUALIZAR TABELAS
SELECT * FROM FUNCIONARIOS
SELECT * FROM PRODUTOS