-- INSERTS 

SELECT * FROM TBL_CIDADE;
SELECT * FROM TBL_FORNECEDOR;
SELECT * FROM TBL_PECA;
SELECT * FROM TBL_PROJETO;
SELECT * FROM TBL_FORNECIMENTO;

-- TABELA CIDADE
INSERT INTO TBL_CIDADE VALUES (11, 'Limeira', 'SP');
INSERT INTO TBL_CIDADE VALUES (12, 'São Paulo', 'SP');