-- INSERTS 
SELECT * FROM TBL_FORNECEDOR;
SELECT * FROM TBL_CIDADE;
SELECT * FROM TBL_PECA;
SELECT * FROM TBL_PROJETO;
SELECT * FROM TBL_FORNECIMENTO;

-- TABELA FORNECEDOR
INSERT INTO TBL_FORNECEDOR VALUES (DEFAULT, 'Kalunga', 'Ativo', 1930234066, 11);
INSERT INTO TBL_FORNECEDOR VALUES (DEFAULT, 'LLC Logistica', 'Inativo', 1130245578, 12);
INSERT INTO TBL_FORNECEDOR VALUES (DEFAULT, 'Velho Barreiro', 'Ativo', 1930324068, 13);
INSERT INTO TBL_FORNECEDOR VALUES (DEFAULT, 'Hyundai', 'Ativo', 1930224545 , 14);

-- TABELA CIDADE
INSERT INTO TBL_CIDADE VALUES (11, 'Limeira', 'SP');
INSERT INTO TBL_CIDADE VALUES (12, 'São Paulo', 'SP');
INSERT INTO TBL_CIDADE VALUES (13,'Rio Claro', 'SP');
INSERT INTO TBL_CIDADE VALUES (14, 'Piracicaba', 'SP');

-- TABELA PECA
INSERT INTO TBL_PECA VALUES (0001, 'Processador', 'Padrão', 300, 13);
INSERT INTO TBL_PECA VALUES (0002, 'Lona', 'Azul', 12, 11);
INSERT INTO TBL_PECA VALUES (0003, 'Cachaça', 'Transparente', 11, 12);
INSERT INTO TBL_PECA VALUES (0004, 'Hyundai Creta', 100, 10000, 14);

-- TABELA PROJETO 
INSERT INTO TBL_PROJETO VALUES (01, 'Eletrônicos', 11);
INSERT INTO TBL_PROJETO VALUES (02, 'Mecânica', 13);
INSERT INTO TBL_PROJETO VALUES (03, 'Escolas', 12);
INSERT INTO TBL_PROJETO VALUES (04, '', 14)

DELETE FROM TBL_PROJETO WHERE PRNOME = ''
-- TABELA FORNECIMENTO 
INSERT INTO TBL_FORNECIMENTO VALUES (8, 0001, 01, 660);
INSERT INTO TBL_FORNECIMENTO VALUES (9, 0002, 03, 10);
INSERT INTO TBL_FORNECIMENTO VALUES (10, 0004, 02, 220);

-- UPDATES
UPDATE TBL_PECA SET PESO = 400 WHERE PNOME = 'Lona'

-- DELETE
DELETE FROM TBL_CIDADE WHERE UF = 'SP'

-- APAGA TODOS OS VALORES E TODAS AS RELAÇÕES PERMITINDO APAGAR CHAVES ESTRANGEIRAS
-- APAGA TAMBÉM AS TABELAS QUE SÃO CHAVE ESTRANGEIRA NA TABELA QUE FOI DADO O TRUNCADE
TRUNCATE TABLE TBL_FORNECEDOR CASCADE
DELETE FROM TBL_FORNECEDOR WHERE FSTATUS = 'Inativo'

-- APAGANDO TODAS AS TABELAS
DROP TABLE TBL_FORNECEDOR;
DROP TABLE TBL_CIDADE;
DROP TABLE TBL_PECA;
DROP TABLE TBL_PROJETO;
DROP TABLE TBL_FORNECIMENTO;