
-- TABELAS
CREATE TABLE TBL_FUNCIONARIOS(
	FCODIGO SERIAL NOT NULL,
	FNOME VARCHAR(50) NOT NULL,
	FSTATUS VARCHAR(50) NOT NULL DEFAULT 'ATIVO',
	FCIDADE VARCHAR(50) NOT NULL,
	PRIMARY KEY (FCODIGO)
);

CREATE TABLE TBL_PECA(
	PCODIGO INT NOT NULL,
	PNOME VARCHAR(30) NOT NULL,
	PCOR VARCHAR(30) NOT NULL,
	PESO REAL NOT NULL,
	PCIDADE VARCHAR(30) NOT NULL,
	PRIMARY KEY(CODIGO)
);

CREATE TABLE TBL_INSTITUICAO(
	ICODIGO INT NOT NULL,
	INOME VARCHAR(30) NOT NULL,
	PRIMARY KEY (ICODIGO)
);

CREATE TABLE TBL_PROJETO(
	PRCODIGO SERIAL NOT NULL,
	PRNOME VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ICODIGO INT NOT NULL,
	PRIMARY KEY (PRCODIGO),
	FOREIGN KEY (ICODIGO) REFERENCES TBL_INSTITUICAO(ICODIGO)
);

CREATE TABLE TBL_FORNECIMENTO(
	
)