
-- create
CREATE TABLE cadfun(
    CODFUN INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL,
    DEPTO CHAR(2),
    FUNCAO CHAR(20),
    SALARIO NUMERIC(10,2),
    FILHOS INT NOT NULL
);

SELECT * FROM cadfun;

-- insert
INSERT INTO cadfun (CODFUN, NOME, DEPTO, FUNCAO, SALARIO, FILHOS)
VALUES (12, 'CARLOS ALBERTO', '3', 'VENDEDOR', 1530.00, 1);

INSERT INTO cadfun (CODFUN, NOME, DEPTO, FUNCAO, SALARIO, FILHOS)
VALUES (15, 'MARCOS HENRIQUE', '2', 'GERENTE', 1985.75, 3);

INSERT INTO cadfun (CODFUN, NOME, DEPTO, FUNCAO, SALARIO, FILHOS)
VALUES (7, 'APARECIDA SILVA', '3', 'SECRETARIA', 1200.50, 2);

INSERT INTO cadfun (CODFUN, NOME, DEPTO, FUNCAO, SALARIO, FILHOS)
VALUES (9, 'SOLANGE PACHECO', '5', 'SUPERVISORA', 1599.51, 5);

INSERT INTO cadfun (CODFUN, NOME, DEPTO, FUNCAO, SALARIO, FILHOS)
VALUES (6, 'MARCELO SOUZA', '3', 'ANALISTA', 2250.11, 3);

INSERT INTO cadfun (CODFUN, NOME, DEPTO, FUNCAO, SALARIO, FILHOS)
VALUES (1, 'CELIA NASCIMENTO', '2', 'SECRETARIA', 1200.5, 3);

INSERT INTO cadfun VALUES(2, 'WILSON DE MACEDO', '3', 'PROGRAMADOR', 1050.00, 5);
INSERT INTO cadfun VALUES(5, 'AUGUSTO SOUZA', '3', 'PROGRAMADOR', 1050.00, 6);
INSERT INTO cadfun VALUES(4, 'CARLOS BASTOS', '5', 'VENDEDOR', 1530.00, 1);
INSERT INTO cadfun VALUES(25, 'PEDRO SILVA', '3', 'SUPERVISOR', 1599.51, 0);
INSERT INTO cadfun VALUES(3, 'ANA BASTOS', '5', 'VENDEDORA', 1530.00, 3);
INSERT INTO cadfun VALUES(10, 'PAULO DA SILVA', '2', 'VENDEDOR', 1530.00, 4);

-- 7. 
SELECT codfun, nome, salario + 250 AS PROJECAO_SALARIAL FROM cadfun;

-- 8.
SELECT * FROM cadfun WHERE funcao = 'ANALISTA';

-- 9.
SELECT * FROM cadfun WHERE salario > 1700.00;

-- 10.
SELECT * FROM cadfun WHERE salario < 1700.00;

-- 11.
SELECT * FROM cadfun WHERE salario = 1700.00;

-- 12.
SELECT * FROM cadfun WHERE funcao = 'PROGRAMADOR' OR funcao = 'ANALISTA';

-- 13.
SELECT * FROM cadfun WHERE funcao = 'PROGRAMADOR' AND salario > 1500 OR funcao = 'ANALISTA' AND salario > 1200;

-- 14.
SELECT * FROM cadfun WHERE NOT funcao = 'PROGRAMADOR' AND NOT funcao = 'ANALISTA';

-- 15.
SELECT * FROM cadfun WHERE filhos BETWEEN 2 AND 4;

-- 16.I
SELECT codfun, nome, salario * 1.25 AS aumento FROM cadfun;

-- 16.II
SELECT * FROM cadfun WHERE (filhos BETWEEN 2 AND 4) AND salario < 2000;

-- 17.
SELECT  * FROM cadfun WHERE filhos < 2 OR filhos > 3;

-- 18.
SELECT * FROM cadfun WHERE (filhos < 2 OR filhos > 3) AND filhos != 0; 

-- 19.
SELECT * FROM cadfun WHERE filhos BETWEEN 2 AND 4






















